### ISSUE TITLE
Plugins are duplicated between here and Community Scripts, which should I use?

### ISSUE THREAD

**Issue by C84186** [stg-annon/StashScripts#2]
Eg -

https://github.com/stg-annon/StashScripts/tree/main/plugins/phashDuplicateTagger

https://github.com/stashapp/CommunityScripts/tree/main/plugins/phashDuplicateTagger

Duplicated across both repos.
I wish to fork + maybe contribute, but I can't tell which repo to use. 

It looks like some commits to the (maybe) upstream CommunityScripts repo get applied here, eg:

 https://github.com/stg-annon/StashScripts/commit/028e2c6a34fa35bfcede73750631d08aea3a5742 
 
 https://github.com/stashapp/CommunityScripts/commit/f3ee199ee97dd2163d80065bc00b2dcdf14a2797

**Comment by stg-annon** [comment]
I've primarily switched to the first repo, the change has been added here as well
