### ISSUE TITLE
[PDT] Consider updating the name

### ISSUE THREAD

**Issue by DogmaDragon** [stg-annon/StashScripts#4]
Now that it doesn't conflict with the one from CommunityScripts, consider changing the name to be more descriptive. 

https://github.com/stg-annon/StashScripts/blob/c2cca9b832b2cc87327fc5bd4f76e6270883ee65/plugins/phashDuplicateTagger/phashDuplicateTagger.yml#L1

**Comment by stg-annon** [comment]
resolved with https://github.com/stg-annon/StashScripts/commit/9086cda7cc993ef5755ac64fd808f005c80373e8
