### ISSUE TITLE
Hip Size Wide

### ISSUE THREAD

**Issue by peterpannimmerland** [stg-annon/StashScripts#7]
Hey,

Hey thanks for the great plugin. so far everything works. unfortunately there is one little thing that I noticed.
All female performers get the tag ‘HipSize.WIDE’ I can't really explain why. The other hip size tags medium and small are not assigned.

It could of course be that all my performers have large hips, but with almost 2000 performers I think there would also be one with small hips.

What can I provide you to analyse this topic?
![image](https://github.com/user-attachments/assets/6a24e7e3-4f67-4e9b-a96d-da53343b7686)
![image](https://github.com/user-attachments/assets/31afa73f-3347-4b49-bb3e-c496d531e429)
![image](https://github.com/user-attachments/assets/771166a1-d817-43e0-8cf3-961f32847fa8)
![image](https://github.com/user-attachments/assets/a1be6b8d-feb0-4792-8c33-47de301c4d8f)

regards

**Comment by stg-annon** [comment]
resolved by 212452425424857848020e07349cb932d5b9b06f
